x-services:
  app_poetry: &app_poetry
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

version: '3.8'
services:
  db:
    image: postgres:15 # 5432
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  web:
    <<: *app_poetry
    command: sh -c "python manage.py migrate && uvicorn conf.asgi:app --host 0.0.0.0 --reload"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data_dev:
  static_volume:
  media_volume:


