# Generated by Django 4.1.5 on 2023-01-11 14:16

import apps.channel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to=apps.channel.models.upload_to, validators=[utils.validators.FileMimeValidator()], verbose_name='Картинка канала')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватный?')),
            ],
            options={
                'verbose_name': 'Каналы',
                'verbose_name_plural': 'Канал',
            },
        ),
        migrations.CreateModel(
            name='UsersChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notification', models.BooleanField(default=False, verbose_name='Уведомления')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], max_length=64, verbose_name='Роль')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channelsmodel', verbose_name='Канал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователи каналов',
                'verbose_name_plural': 'Пользователь канала',
            },
        ),
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_like', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название')),
                ('source_media', models.FileField(upload_to=apps.channel.models.upload_to, verbose_name='Исходное медиа')),
                ('compressed_media', models.FileField(upload_to=apps.channel.models.upload_to, verbose_name='сжатое медиа')),
                ('user_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.userschannelmodel', verbose_name='Пользователь канала')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_like', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Полный тест')),
                ('previous_text', models.CharField(max_length=1024, verbose_name='Сокращенный текст')),
                ('user_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.userschannelmodel', verbose_name='Пользователь канала')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
