# Generated by Django 4.1.5 on 2023-01-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'verbose_name': 'Публикации каналов', 'verbose_name_plural': 'Публикация канала'},
        ),
        migrations.AlterModelOptions(
            name='mediamodel',
            options={'verbose_name': 'Медиа каналов', 'verbose_name_plural': 'Медиа канала'},
        ),
    ]
