# Generated by Django 4.1.5 on 2023-01-11 14:27

import apps.channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_articlemodel_options_alter_mediamodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='compressed_media',
            field=models.FileField(upload_to=apps.channel.models.upload_content_to, verbose_name='сжатое медиа'),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='source_media',
            field=models.FileField(upload_to=apps.channel.models.upload_content_to, verbose_name='Исходное медиа'),
        ),
    ]
