# Generated by Django 4.1.5 on 2023-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_mediamodel_compressed_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsmodel',
            name='link_name',
            field=models.CharField(default='sdfsd', max_length=128, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channelsmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
