# Generated by Django 4.1.5 on 2023-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_channelsmodel_link_name_alter_channelsmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsmodel',
            name='link_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Ссылка на канал'),
        ),
    ]
